"""
Phase 4a — HarnessBuilder.

Materializes a Claude-ready bundle for a deliverable:

  <bundle_root>/<harness_id>/
    ├── problem_statement.md        (from Phase 3.5 Meta-LLM)
    ├── CLAUDE.md                   (executor-role instructions for Claude)
    ├── bundle.json                 (machine-readable manifest)
    ├── context/
    │    ├── 01_<slug>.md           (top value_score anchor)
    │    ├── 02_<slug>.md
    │    └── …
    └── pitfalls/                   (optional — only if redflag anchors exist)
         └── <slug>.md

Claude Code consumes this via the `/pmis-harness` slash command, which reads
the bundle path and starts a planning session. No execution happens inside
PMIS — Claude Code does the work.

Division of labor:
  PMIS  — builds the bundle (this module) including a CLAUDE.md that
           instructs Claude to draft plan.md, show it for approval, then
           execute steps tagged [CLAUDE] / [USER] / [REVIEW].
  Claude — reads CLAUDE.md + problem_statement.md, drafts plan, executes.
"""

from __future__ import annotations

import json
import logging
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("pmis.harness.builder")


CLAUDE_MD_TEMPLATE = """\
# PMIS Harness — Executor Instructions

You are running inside a PMIS-generated harness for the deliverable:

**{deliverable_name}** ({deliverable_id}) · Project: {project_name}

## How to run this harness

1. **Read `problem_statement.md` and the `context/` folder.** That is the
   complete briefing PMIS composed from memory. Do not invent additional
   context that's not there.
2. **Draft `plan.md`** with discrete steps. Tag each step:
   - `[CLAUDE]` — you will execute this automatically
   - `[USER]` — requires the human; skip and flag
   - `[REVIEW]` — execute, then pause for human approval before continuing
3. **Show `plan.md` to the user and ask for approval.** Do not start
   executing until the user says go.
4. **Execute approved `[CLAUDE]` steps sequentially.** Pause at `[REVIEW]`.
   Skip `[USER]` and list them at the end.
5. **Write `run_log.md`** with what you did, what the user needs to do, and
   any issues. Keep it terse.
6. **Do NOT touch files outside this deliverable's scope** (listed in
   `problem_statement.md` under "Out of scope"). When in doubt, ask.

## Pitfalls

{pitfalls_block}

## Telemetry

When you finish, call back to PMIS:
```
curl -s -X POST \\
  "http://localhost:8100/api/harness/{harness_id}/record-run" \\
  -H "Content-Type: application/json" \\
  -d '{{"thumb": "up_or_down", "outcome": "goal_achieved_or_unchanged", "notes": "short summary"}}'
```

The user can also thumb this harness from the PMIS wiki widget — either
signal feeds the Phase 5 value_score loop.

---
Generated by PMIS HarnessBuilder at {generated_at}.
"""


class HarnessBuilder:
    def __init__(self, db, embedder, hyperparams: Optional[Dict[str, Any]] = None,
                 bundle_root: Optional[str] = None,
                 meta_composer=None):
        self.db = db
        self.embedder = embedder
        self.hp = hyperparams or {}
        default_root = str(Path(__file__).resolve().parents[2] / ".pmis_harnesses")
        self.bundle_root = Path(self.hp.get("harness_bundle_root", bundle_root or default_root))
        self.bundle_root.mkdir(parents=True, exist_ok=True)
        self._meta_composer = meta_composer  # optional; lazy-construct if None

    # ------------------------------------------------------------------

    def build(
        self,
        deliverable_id: str,
        use_llm: bool = False,
        title_override: Optional[str] = None,
        trigger_source: str = "manual",
        pattern_signature: str = "",
    ) -> Dict[str, Any]:
        """Materialize a harness bundle for `deliverable_id`. Registers a row
        in agent_harnesses and returns the harness record."""
        deliverable = self.db.get_deliverable(deliverable_id)
        if not deliverable:
            raise ValueError(f"deliverable_not_found: {deliverable_id}")

        composer = self._get_meta_composer()
        bundle = composer.compose(deliverable_id, use_llm=use_llm)

        # Allocate id + path BEFORE writing so we can log the path
        import uuid as _uuid
        harness_id = _uuid.uuid4().hex[:12]
        bundle_path = self.bundle_root / harness_id
        bundle_path.mkdir(parents=True, exist_ok=True)
        (bundle_path / "context").mkdir(exist_ok=True)

        # ── problem_statement.md
        (bundle_path / "problem_statement.md").write_text(bundle.problem_statement_md, encoding="utf-8")

        # ── context/*.md  (one per anchor, ranked by value_score+similarity)
        positive_anchors = [a for a in bundle.anchors_used if not a.get("is_negative")]
        negative_anchors = [a for a in bundle.anchors_used if a.get("is_negative")]
        context_manifest: List[Dict[str, Any]] = []
        for idx, a in enumerate(positive_anchors, start=1):
            preview = (a.get("preview") or "").strip()
            full = self._fetch_full_content(a.get("node_id", "")) or preview
            slug = _slugify(preview.split(".")[0] or f"anchor-{idx}")
            fname = f"{idx:02d}_{slug}.md"
            body = self._render_context_file(a, full, idx, kind="positive")
            (bundle_path / "context" / fname).write_text(body, encoding="utf-8")
            context_manifest.append({"file": f"context/{fname}", **a})

        pitfalls_dir = bundle_path / "pitfalls"
        pitfalls_manifest: List[Dict[str, Any]] = []
        pitfalls_block_lines: List[str] = []
        if negative_anchors:
            pitfalls_dir.mkdir(exist_ok=True)
            for idx, n in enumerate(negative_anchors, start=1):
                preview = (n.get("preview") or "").strip()
                full = self._fetch_full_content(n.get("node_id", "")) or preview
                slug = _slugify(preview.split(".")[0] or f"pitfall-{idx}")
                fname = f"{idx:02d}_{slug}.md"
                body = self._render_context_file(n, full, idx, kind="pitfall")
                (pitfalls_dir / fname).write_text(body, encoding="utf-8")
                pitfalls_manifest.append({"file": f"pitfalls/{fname}", **n})
                pitfalls_block_lines.append(f"- `pitfalls/{fname}` — {preview[:100]}")
        else:
            pitfalls_block_lines.append("_None logged for this deliverable._")

        # ── bundle.json (machine-readable)
        manifest = {
            "harness_id": harness_id,
            "deliverable_id": deliverable_id,
            "deliverable_name": deliverable.get("name", ""),
            "project_id": deliverable.get("project_id", ""),
            "project_name": deliverable.get("project_name", ""),
            "generated_at": bundle.generated_at,
            "mode": bundle.mode,
            "model_used": bundle.model_used,
            "latest_segment": bundle.latest_segment,
            "context": context_manifest,
            "pitfalls": pitfalls_manifest,
            "composer_version": bundle.composer_version,
            "trigger_source": trigger_source,
            "pattern_signature": pattern_signature,
        }
        (bundle_path / "bundle.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

        # ── CLAUDE.md (executor role)
        (bundle_path / "CLAUDE.md").write_text(CLAUDE_MD_TEMPLATE.format(
            deliverable_name=deliverable.get("name", ""),
            deliverable_id=deliverable_id,
            project_name=deliverable.get("project_name", ""),
            pitfalls_block="\n".join(pitfalls_block_lines),
            harness_id=harness_id,
            generated_at=bundle.generated_at,
        ), encoding="utf-8")

        # ── DB row
        title = title_override or f"Harness for {deliverable.get('name','')}"
        hid = self.db.create_harness({
            "id": harness_id,
            "deliverable_id": deliverable_id,
            "project_id": deliverable.get("project_id", ""),
            "title": title,
            "bundle_path": str(bundle_path),
            "problem_statement_md": bundle.problem_statement_md,
            "anchors_used": bundle.anchors_used,
            "pattern_signature": pattern_signature,
            "trigger_source": trigger_source,
            "pre_run_features": {
                "anchor_count": len(positive_anchors),
                "pitfall_count": len(negative_anchors),
                "latest_segment_length_secs": (bundle.latest_segment or {}).get("length_secs", 0),
                "mode": bundle.mode,
            },
            "mode": bundle.mode,
            "model_used": bundle.model_used,
        })

        return self.db.get_harness(hid)

    # ------------------------------------------------------------------

    def _get_meta_composer(self):
        if self._meta_composer is not None:
            return self._meta_composer
        from claude_integration.meta_composer import ProblemStatementComposer
        self._meta_composer = ProblemStatementComposer(
            self.db, self.embedder, hyperparams=self.hp,
        )
        return self._meta_composer

    def _fetch_full_content(self, node_id: str) -> str:
        if not node_id:
            return ""
        node = self.db.get_node(node_id)
        return (node or {}).get("content", "") or ""

    def _render_context_file(
        self, anchor: Dict[str, Any], full_content: str, idx: int, kind: str = "positive"
    ) -> str:
        header = "# Pitfall" if kind == "pitfall" else f"# Context anchor {idx}"
        meta_bits = []
        if anchor.get("similarity") is not None:
            meta_bits.append(f"similarity={float(anchor['similarity']):.2f}")
        if anchor.get("value_score") is not None:
            meta_bits.append(f"value_score={float(anchor['value_score']):.2f}")
        if anchor.get("automatability") is not None:
            meta_bits.append(f"automatability={float(anchor['automatability']):.2f}")
        if anchor.get("value_feedback") is not None:
            meta_bits.append(f"feedback={float(anchor['value_feedback']):+.2f}")
        if anchor.get("node_id"):
            meta_bits.append(f"node_id={anchor['node_id']}")
        meta = " · ".join(meta_bits) if meta_bits else ""
        return f"{header}\n\n*{meta}*\n\n---\n\n{full_content.strip()}\n"


# ── helpers ──────────────────────────────────────────────────────────

def _slugify(text: str, max_len: int = 60) -> str:
    s = re.sub(r"[^\w\s-]", "", (text or "").lower())
    s = re.sub(r"\s+", "-", s).strip("-")
    return (s[:max_len] or "anchor").rstrip("-")
